apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapitest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sapitest
  template:
    metadata:
      labels:
        app: k8sapitest
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: k8sapitest
          image: ghcr.io/emregdl/k8sapitest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000